(function(){
const $=id=>document.getElementById(id);
const REPORTS=[["business_report","Business Report","Vendite, sessioni, conversioni"],["orders","Report ordini","Ordini e quantità vendute"],["transactions","Transazioni / pagamenti","Commissioni, rimborsi, accrediti"],["ad_invoices","Fatture Ads","Spesa pubblicitaria fatturata"],["sponsored_products","Sponsored Products","Campagne SP"],["sponsored_brands","Sponsored Brands","Campagne SB"],["sponsored_display","Sponsored Display","Campagne SD"],["search_terms","Search Terms","Termini di ricerca"],["inventory","Inventario","Stock e SKU"],["product_costs","Costi BipBop","Produzione, packaging, spedizione"]];
let state={reports:[],counts:{},errors:[]};
function parseCSV(text){const rows=[];let row=[],cur="",q=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c=='"'&&q&&next=='"'){cur+='"';i++;continue}if(c=='"'){q=!q;continue}if(c==","&&!q){row.push(cur);cur="";continue}if((c=="\n"||c=="\r")&&!q){if(c=="\r"&&next=="\n")i++;row.push(cur);cur="";if(row.some(x=>String(x).trim()!=""))rows.push(row);row=[];continue}cur+=c}row.push(cur);if(row.some(x=>String(x).trim()!=""))rows.push(row);let hi=0,max=0;rows.forEach((r,i)=>{if(r.length>max){max=r.length;hi=i}});const headers=rows[hi].map((h,i)=>String(h||"").trim()||"col_"+(i+1));const data=rows.slice(hi+1).map(r=>{const o={};headers.forEach((h,i)=>o[h]=r[i]??"");return o}).filter(o=>Object.values(o).some(v=>String(v).trim()!=""));return{headers,data}}
function readFile(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||""));r.onerror=()=>rej(r.error);r.readAsText(file,"UTF-8")})}
function label(type){return (REPORTS.find(r=>r[0]===type)||[type,type])[1]}
function renderImportGrid(){ $("importGrid").innerHTML=REPORTS.map(([type,label,desc])=>`<div class="import-box"><h4>${label}</h4><p class="hint">${desc}</p><input id="file_${type}" type="file" accept=".csv"><button data-import="${type}">Importa / sostituisci</button><button class="dangerBtn" data-clear="${type}">Elimina report</button></div>`).join("");document.querySelectorAll("[data-import]").forEach(b=>b.onclick=()=>importReport(b.dataset.import));document.querySelectorAll("[data-clear]").forEach(b=>b.onclick=()=>clearReport(b.dataset.clear))}
async function importReport(type){try{const file=$("file_"+type)?.files?.[0];if(!file)throw new Error("Seleziona un file CSV.");const parsed=parseCSV(await readFile(file));await window.BipBopSupabase.replaceReport(type,file.name,parsed.headers,parsed.data);$("importLog").innerHTML=`✅ ${label(type)} importato: ${parsed.data.length} righe, ${parsed.headers.length} colonne.`;await refresh()}catch(e){err(e);alert(e.message||e)}}
async function clearReport(type){if(!confirm("Eliminare il report "+label(type)+"?"))return;try{await window.BipBopSupabase.clearReport(type);$("importLog").innerHTML=`Report ${label(type)} eliminato.`;await refresh()}catch(e){err(e);alert(e.message||e)}}
async function refresh(){try{const cfg=window.BipBopSupabase.getConfig();$("cloudBadge").textContent=cfg.url&&cfg.key?"Cloud configurato":"Cloud non collegato";$("cloudBadge").className="badge "+(cfg.url&&cfg.key?"ok":"bad");if(!cfg.url||!cfg.key){render();return}state.reports=await window.BipBopSupabase.listReports();state.counts={};for(const [type] of REPORTS){state.counts[type]=await window.BipBopSupabase.countReport(type)}render()}catch(e){err(e)}}
function render(){const imported=REPORTS.filter(([type])=>(state.counts[type]||0)>0).length;$("headline").textContent=imported?`${imported} report importati`:"Report Center pulito";$("subtitle").textContent=imported?"I dati importati sono separati per tipo di report.":"Importa i CSV Amazon uno alla volta.";$("kpis").innerHTML=[["Report importati",imported+" / "+REPORTS.length],["Righe totali",Object.values(state.counts).reduce((a,b)=>a+(b||0),0)],["Business Report",state.counts.business_report||0],["Fatture Ads",state.counts.ad_invoices||0],["Sponsored Products",state.counts.sponsored_products||0],["Search Terms",state.counts.search_terms||0],["Inventario",state.counts.inventory||0],["Costi",state.counts.product_costs||0]].map(x=>`<div class="kpi"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");$("missingBox").innerHTML=REPORTS.map(([type,label,desc])=>`<div class="action"><b>${label}</b> — ${desc}<br>${(state.counts[type]||0)>0?`<span class="status-ok">✓ importato</span> — ${state.counts[type]} righe`:`<span class="status-missing">mancante</span>`}</div>`).join("");$("reportsTable").innerHTML=state.reports.length?`<table><tr><th>Report</th><th>File</th><th>Righe</th><th>Colonne</th><th>Importato</th></tr>${state.reports.map(r=>`<tr><td><span class="pill">${label(r.report_type)}</span></td><td>${r.file_name||""}</td><td>${r.row_count||0}</td><td>${Array.isArray(r.headers)?r.headers.length:""}</td><td>${new Date(r.imported_at).toLocaleString("it-IT")}</td></tr>`).join("")}</table>`:`<div class="action">Nessun report importato.</div>`;$("diagnosticBox").innerHTML=`<div class="action"><b>SOLO TABELLE bb14</b><br>Import log: ${state.reports.length}<br>Raw rows: ${Object.values(state.counts).reduce((a,b)=>a+(b||0),0)}<br>Tipi report configurati: ${REPORTS.length}</div>`;$("errorBox").textContent=state.errors.length?state.errors.join("\n"):"Nessun errore."}
function err(e){state.errors.push(String(e?.message||e));render();console.error(e)}
function init(){renderImportGrid();document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.view).classList.add("active");$("pageTitle").textContent=b.textContent.replace(/[📊📥📁🧪⚙️]/g,"").trim()});$("refreshBtn").onclick=refresh;const cfg=window.BipBopSupabase.getConfig();$("supabaseUrl").value=cfg.url||"";$("supabaseKey").value=cfg.key||"";$("saveSetup").onclick=()=>{window.BipBopSupabase.saveConfig({url:$("supabaseUrl").value.trim(),key:$("supabaseKey").value.trim()});alert("Configurazione salvata");refresh()};refresh()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();